<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#numpy-ndarray" data-toc-modified-id="numpy-ndarray-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>numpy ndarray</a></span><ul class="toc-item"><li><span><a href="#Creating-arrays" data-toc-modified-id="Creating-arrays-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Creating arrays</a></span></li><li><span><a href="#Data-types" data-toc-modified-id="Data-types-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Data types</a></span></li><li><span><a href="#Operations-between-Arrays-and-Scalar" data-toc-modified-id="Operations-between-Arrays-and-Scalar-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Operations between Arrays and Scalar</a></span></li><li><span><a href="#Basic-index-and-slicing" data-toc-modified-id="Basic-index-and-slicing-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Basic index and slicing</a></span><ul class="toc-item"><li><span><a href="#Indexing-with-slices." data-toc-modified-id="Indexing-with-slices.-1.4.1"><span class="toc-item-num">1.4.1&nbsp;&nbsp;</span>Indexing with slices.</a></span></li></ul></li><li><span><a href="#Boolean-indexing" data-toc-modified-id="Boolean-indexing-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>Boolean indexing</a></span></li><li><span><a href="#Fancy-indexing" data-toc-modified-id="Fancy-indexing-1.6"><span class="toc-item-num">1.6&nbsp;&nbsp;</span>Fancy indexing</a></span></li><li><span><a href="#Transposing-arrays-and-swapping-axes." data-toc-modified-id="Transposing-arrays-and-swapping-axes.-1.7"><span class="toc-item-num">1.7&nbsp;&nbsp;</span>Transposing arrays and swapping axes.</a></span></li><li><span><a href="#Universal-functions" data-toc-modified-id="Universal-functions-1.8"><span class="toc-item-num">1.8&nbsp;&nbsp;</span>Universal functions</a></span></li></ul></li><li><span><a href="#Data-processing-using-arrays" data-toc-modified-id="Data-processing-using-arrays-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Data processing using arrays</a></span><ul class="toc-item"><li><span><a href="#Expressing-conditional-logic-as-array-operations." data-toc-modified-id="Expressing-conditional-logic-as-array-operations.-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Expressing conditional logic as array operations.</a></span></li><li><span><a href="#Mathematical-and-statistical-methods" data-toc-modified-id="Mathematical-and-statistical-methods-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Mathematical and statistical methods</a></span></li><li><span><a href="#Unique-and-set-logic" data-toc-modified-id="Unique-and-set-logic-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Unique and set logic</a></span></li></ul></li><li><span><a href="#File-input-and-output" data-toc-modified-id="File-input-and-output-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>File input and output</a></span><ul class="toc-item"><li><span><a href="#Storing-arrays-on-disk-in-binary-form." data-toc-modified-id="Storing-arrays-on-disk-in-binary-form.-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Storing arrays on disk in binary form.</a></span></li></ul></li><li><span><a href="#Linear-algebra" data-toc-modified-id="Linear-algebra-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Linear algebra</a></span></li><li><span><a href="#Random-number-generator" data-toc-modified-id="Random-number-generator-5"><span class="toc-item-num">5&nbsp;&nbsp;</span><strong>Random number generator</strong></a></span><ul class="toc-item"><li><span><a href="#Random-walks" data-toc-modified-id="Random-walks-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span><strong>Random walks</strong></a></span></li></ul></li></ul></div>

- numpy (numerical python)

- high performance scientific computing and data analysis
- `ndarray` = fast space-efficient multidim array with
    - vectorized arithmetic operations (no loops)
    - sophisticated broadcasting capabilities
- sorting, unique, set operation
- data alignment
- reading / writing arrays to disk and memory-mapped files
- linear algebra
- random number generation
- FFT, ...
- tools for integrating code with C, C++, Fortran
    - easy C API to call external libraries

In [1]:
import numpy as np

# numpy ndarray

- ndarray = N-Dim array object

## Creating arrays

In [2]:
# From sequence-like object to ndarray.
data1 = [6, 7.5, 8, 0, 1]

arr1 = np.array(data1)

print("arr1=", arr1)
# It's like a vector not a matrix.
print("arr1.shape=", arr1.shape)
print("arr1.dtype=", arr1.dtype)

arr1= [6.  7.5 8.  0.  1. ]
arr1.shape= (5,)
arr1.dtype= float64


In [3]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)

print("arr2=\n", arr2)
print("arr2.shape=", arr2.shape)
# np.array() tries to infer the right type, if not done explicitly.
print("arr2.dtype=", arr2.dtype)

arr2=
 [[1 2 3 4]
 [5 6 7 8]]
arr2.shape= (2, 4)
arr2.dtype= int64


In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [6]:
np.zeros_like(arr2)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [7]:
# Returns unitialized garbage values.
np.empty((2, 3, 2))

array([[[2.48464981e-316, 0.00000000e+000],
        [1.03977794e-312, 9.54898106e-313],
        [1.06099790e-312, 1.01855798e-312]],

       [[1.23075756e-312, 1.06099790e-312],
        [1.03977794e-312, 9.76118064e-313],
        [1.18831764e-312, 1.90979621e-312]]])

In [8]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Data types

- map directly onto machine representation
    - `int*, uint*`
    - `float*`
    - `complex*`
    - `bool`
    - `object` (python object)
    - `string*` (fixed length string)
    - `unicode*` (fixed length unicode, num of bytes depending on machine)
- easy to read / write to disk
- easy to interface with low-level code in C and Fortran


In [10]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
print(arr1)

[1. 2. 3.]


In [11]:
arr2 = np.array([-1, 2, 3], dtype=np.int32)
print(arr2)

[-1  2  3]


In [12]:
arr2 = np.array([-1, 2, 3], dtype=np.uint32)
print(arr2)

[4294967295          2          3]


In [13]:
# Cast an array from one type to another.
# It always create a new array even if dtype is not changed.
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(arr.dtype)

float_arr = arr.astype(np.float64)
print(float_arr)
print(float_arr.dtype)

[1 2 3 4 5]
int64
[1. 2. 3. 4. 5.]
float64


In [14]:
str_arr = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
print(str_arr)
print(str_arr.dtype)

print(str_arr.astype(float))

[b'1.25' b'-9.6' b'42']
|S4
[ 1.25 -9.6  42.  ]


## Operations between Arrays and Scalar

- One can express operations on data without for loops

In [15]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

print(arr + arr)
# Broadcast.
print(1 / arr)
print(arr * arr)
print(arr ** 0.5)

[[ 2.  4.  6.]
 [ 8. 10. 12.]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


## Basic index and slicing

In [16]:
arr = np.arange(10)

print(arr)

print(arr[5])
print(arr[5:8])

[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]


In [17]:
# Broadcasting write.
arr[5:8]= 12
print(arr)

[ 0  1  2  3  4 12 12 12  8  9]


In [18]:
# Slices are "views" on the original array. No data is copied.

arr_slice = arr[5:8]
print(arr_slice)

arr_slice[1] = 12345
print(arr_slice)

arr_slice[:] = 64
print(arr_slice)

print(arr)

[12 12 12]
[   12 12345    12]
[64 64 64]
[ 0  1  2  3  4 64 64 64  8  9]


In [19]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
print(arr2d[2])

[7 8 9]


In [21]:
print(arr2d[2][0])

7


In [22]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3d)
print(arr3d.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [23]:
# Fixing the first index, returns a 2x3 array.
print(arr3d[0])

[[1 2 3]
 [4 5 6]]


In [24]:
arr3d[0] = 42

print(arr3d)

[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]


In [25]:
# Return all the values whose indices start with (1, 0), i.e.,
# a 1-d array.
print(arr3d[1][0])
print(arr3d[1, 0])

[7 8 9]
[7 8 9]


### Indexing with slices.

In [26]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
# Slice first index, i.e., columns.
print(arr2d[:2])
print(arr2d[:2].shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [28]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [29]:
arr2d[1, :2]

array([4, 5])

In [30]:
arr2d[2, :1]

array([7])

In [31]:
# A colon : means "the entire axis"
arr2d[:, :1]

array([[1],
       [4],
       [7]])

## Boolean indexing

In [32]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

print(str(names))
print(repr(names))

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')


In [33]:
np.random.seed(42)
# Normal data.
data = np.random.randn(7, 4)
print(data)

[[ 0.49671415 -0.1382643   0.64768854  1.52302986]
 [-0.23415337 -0.23413696  1.57921282  0.76743473]
 [-0.46947439  0.54256004 -0.46341769 -0.46572975]
 [ 0.24196227 -1.91328024 -1.72491783 -0.56228753]
 [-1.01283112  0.31424733 -0.90802408 -1.4123037 ]
 [ 1.46564877 -0.2257763   0.0675282  -1.42474819]
 [-0.54438272  0.11092259 -1.15099358  0.37569802]]


In [34]:
print(names)
names == "Bob"

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']


array([ True, False, False,  True, False, False, False])

In [35]:
data[names == "Bob"]

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986],
       [ 0.24196227, -1.91328024, -1.72491783, -0.56228753]])

In [36]:
data[names == "Bob", 2:]

array([[ 0.64768854,  1.52302986],
       [-1.72491783, -0.56228753]])

In [37]:
names != "Bob"

array([False,  True,  True, False,  True,  True,  True])

In [38]:
print(~(names == "Bob"))
data[~(names == "Bob")]

[False  True  True False  True  True  True]


array([[-0.23415337, -0.23413696,  1.57921282,  0.76743473],
       [-0.46947439,  0.54256004, -0.46341769, -0.46572975],
       [-1.01283112,  0.31424733, -0.90802408, -1.4123037 ],
       [ 1.46564877, -0.2257763 ,  0.0675282 , -1.42474819],
       [-0.54438272,  0.11092259, -1.15099358,  0.37569802]])

In [39]:
data

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986],
       [-0.23415337, -0.23413696,  1.57921282,  0.76743473],
       [-0.46947439,  0.54256004, -0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024, -1.72491783, -0.56228753],
       [-1.01283112,  0.31424733, -0.90802408, -1.4123037 ],
       [ 1.46564877, -0.2257763 ,  0.0675282 , -1.42474819],
       [-0.54438272,  0.11092259, -1.15099358,  0.37569802]])

In [40]:
data[data < 0] = 0
data

array([[0.49671415, 0.        , 0.64768854, 1.52302986],
       [0.        , 0.        , 1.57921282, 0.76743473],
       [0.        , 0.54256004, 0.        , 0.        ],
       [0.24196227, 0.        , 0.        , 0.        ],
       [0.        , 0.31424733, 0.        , 0.        ],
       [1.46564877, 0.        , 0.0675282 , 0.        ],
       [0.        , 0.11092259, 0.        , 0.37569802]])

## Fancy indexing

- One can index using integer arrays

In [41]:
arr = np.empty((8, 4))

In [42]:
for i in range(8):
    arr[i] = i

print(arr)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [43]:
# Select rows using certain indices.
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [44]:
# Negative indices work as expected.
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [45]:
arr = np.arange(32).reshape((8, 4))

print(str(arr))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [46]:
# WARNING: It doesn't select 4 rows and 4 columns.
# It gets elements (1, 0), (5, 3), (7, 1), (2, 2).
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [47]:
# To select 4 rows and 4 columns.
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [48]:
help(np.ix_)

Help on function ix_ in module numpy:

ix_(*args)
    Construct an open mesh from multiple sequences.
    
    This function takes N 1-D sequences and returns N outputs with N
    dimensions each, such that the shape is 1 in all but one dimension
    and the dimension with the non-unit shape value cycles through all
    N dimensions.
    
    Using `ix_` one can quickly construct index arrays that will index
    the cross product. ``a[np.ix_([1,3],[2,5])]`` returns the array
    ``[[a[1,2] a[1,5]], [a[3,2] a[3,5]]]``.
    
    Parameters
    ----------
    args : 1-D sequences
        Each sequence should be of integer or boolean type.
        Boolean sequences will be interpreted as boolean masks for the
        corresponding dimension (equivalent to passing in
        ``np.nonzero(boolean_sequence)``).
    
    Returns
    -------
    out : tuple of ndarrays
        N arrays with N dimensions each, with N the number of input
        sequences. Together these arrays form an open mesh.

In [49]:
# np.ix_() converts indices.
idxs = np.ix_([1, 5, 7, 2], [0, 3, 1, 2])
print(idxs)

print(arr[idxs])

(array([[1],
       [5],
       [7],
       [2]]), array([[0, 3, 1, 2]]))
[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


## Transposing arrays and swapping axes.

In [50]:
arr = np.arange(15).reshape((3, 5))
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [51]:
print(arr.T)

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [52]:
np.dot(arr.T, arr)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [53]:
arr = np.arange(16).reshape((2, 2, 4))
print(arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


## Universal functions

- ufunc performs elementwise operations on data in ndarrays

In [54]:
arr = np.arange(10)

print(np.sqrt(arr))
print(np.exp(arr))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


In [55]:
np.random.seed(42)
x = np.random.randn(8)
y = np.random.randn(8)

print(x)
print(y)

print(np.maximum(x, y))

[ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337 -0.23413696
  1.57921282  0.76743473]
[-0.46947439  0.54256004 -0.46341769 -0.46572975  0.24196227 -1.91328024
 -1.72491783 -0.56228753]
[ 0.49671415  0.54256004  0.64768854  1.52302986  0.24196227 -0.23413696
  1.57921282  0.76743473]


In [56]:
np.add(x, y)

array([ 0.02723977,  0.40429574,  0.18427085,  1.0573001 ,  0.0078089 ,
       -2.1474172 , -0.14570502,  0.2051472 ])

In [57]:
np.greater(x, y)

array([ True, False,  True,  True, False,  True,  True,  True])

In [58]:
np.not_equal(x, y)

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [59]:
np.logical_xor(
    np.not_equal(x, y),
    np.greater(x, y))

array([False,  True, False, False,  True, False, False, False])

# Data processing using arrays

In [60]:
# Evaluate 

# - Pick 1000 equi-spaced points between [-5, 5].
points = np.arange(-5, 5, 0.01)
print("points=", points[:5])

# - Create a grid of points.
xs, ys = np.meshgrid(points, points)
print("xs=\n", xs)
print("ys=\n", ys)

# - Evaluate function on a grid.
z = np.sqrt(xs ** 2 + ys ** 2)

points= [-5.   -4.99 -4.98 -4.97 -4.96]
xs=
 [[-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 ...
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]]
ys=
 [[-5.   -5.   -5.   ... -5.   -5.   -5.  ]
 [-4.99 -4.99 -4.99 ... -4.99 -4.99 -4.99]
 [-4.98 -4.98 -4.98 ... -4.98 -4.98 -4.98]
 ...
 [ 4.97  4.97  4.97 ...  4.97  4.97  4.97]
 [ 4.98  4.98  4.98 ...  4.98  4.98  4.98]
 [ 4.99  4.99  4.99 ...  4.99  4.99  4.99]]


In [61]:
import matplotlib.pyplot as plt

plt.imshow(z, cmap=plt.cm.gray)
plt.colorbar()
plt.title("hello")

ModuleNotFoundError: No module named 'matplotlib'

## Expressing conditional logic as array operations.

- `numpy.where` is vectorized form of `if-then-else`

In [ ]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
print([round(x, 3) for x in result])

# This is an array.
print(np.where(cond, xarr, yarr))

In [ ]:
np.random.seed(42)
arr = np.random.randn(4, 4)

print(arr)

In [ ]:
np.where(arr > 0, 2, -2)

In [ ]:
# Note that the operation is vectorized, thus one array is let pass.
np.where(arr > 0, 2, arr)

## Mathematical and statistical methods

In [ ]:
np.random.seed(42)
arr = np.random.randn(5, 4)

# One can call the method on the array or the np function.
print(arr.mean())
print(np.mean(arr))

In [ ]:
arr.mean(axis=1)

In [ ]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print(arr)

# Cumsum on different axis.
print(arr.cumsum(axis=0))
print(arr.cumsum(axis=1))

In [ ]:
arr = np.random.randn(100)

# Sum all positive numbers.
(arr > 0).sum()

In [ ]:
bools = np.array([False, False, True, False])

print(bools.any())
print(bools.all())

In [ ]:
## Sorting.

In [ ]:
np.random.seed(8)
arr = np.random.randn(8)
print(arr)
arr.sort()
print(arr)

In [ ]:
arr = np.random.randn(5, 3)
print(arr)

In [ ]:
arr.sort(axis=1)
print(arr)

## Unique and set logic

In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

print(np.unique(names))

In [ ]:
values1 = np.array([6, 0, 0, 3, 2, 5, 6])
print(values1)

# Check memership of values in values1 wrt a given set.
print(np.in1d(values1, [2, 3, 6]))

In [ ]:
values2 = np.array([6, 1, 7, 3, 2, 5, 6])
print("values1=", values1)
print("values2=", values2)

print("intersect=", np.intersect1d(values1, values2))
print("union=", np.union1d(values1, values2))
# A - B
print("diff=", np.setdiff1d(values1, values2))
# Symmetric difference: elements that in either of arrays, but not both.
print("xor=", np.setxor1d(values1, values2))

# File input and output

## Storing arrays on disk in binary form.

In [ ]:
arr = np.arange(10)
print(arr)
np.save("some_array.npy", arr)

In [ ]:
arr2 = np.load("some_array.npy")
print(arr2)

In [ ]:
np.savez("some_array_lazy.npz", arr2)

# Linear algebra

In [ ]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
print("x=\n", x)
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print("y=\n", y)

In [ ]:
print(x.dot(y))
print(np.dot(x, y))

In [ ]:
from numpy.linalg import inv, qr

np.random.seed(42)

X = np.random.randn(5, 5)
mat = X.T.dot(X)
print("mat=\n", mat)

In [ ]:
# Inverse.
inv(mat)

In [ ]:
q, r = qr(mat)
print("q=\n", q)
print("r=\n", r)

In [ ]:
print(np.diag(mat))

In [ ]:
print(np.trace(mat))

In [ ]:
print(np.eig(mat))

In [ ]:
print(np.svd(mat))

# **Random number generator**

## **Random walks**